# Generated by Django 4.0.4 on 2022-05-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_document_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='owner',
            new_name='user',
        ),
    ]
