# Generated by Django 4.0.4 on 2022-05-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_rename_owner_document_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCloudUser',
        ),
    ]
